<div class="guitar2">				
    <img class="img-responsive" src="images/guitar2.jpg" alt="guitar">
</div>
<div class="about-content">					
    <h2>A Trajetória</h2>
    <p>Cantor e compositor brasileiro, nascido em 12 de Julho de 1983, na cidade de Itumbiara-GO, graduado em Sistemas de Informação,  Acácio Vilela Rosa começou a cantar e tocar violão aos 8 anos de idade por influência de seu pai, também músico. Mais tarde, aos 16, decide dar início a sua carreira musical.</p>
    <p>Em 2000, formou sua primeira banda de rock com a qual fazia "cover" de artistas dos anos 80 e 90 do cenário nacional e internacional como: Legião Urbana, Titãs, Guns n’ Roses, Bon Jovi, entre outros. Até em meados de 2007, participou ainda de formações independentes. Em 2008, decide seguir sua carreira como artista solo, afim de trazer para sua música, originalidade e influências como: Legião Urbana, Engenheiros do Hawaii, Bon Jovi, Coldplay, U2 e A-ha.</p>
    <p>Grava seu primeiro trabalho no ano de 2011, disco com 13 faixas acústicas de versões "cover" de grandes nomes do rock. O disco conta com hits como: Hotel California (Eagles), Wherever You Will Go (The Calling) e Use Somebody (King of Leon).</p>
    <p>Atualmente trabalha na produção de seu primeiro projeto autoral que leva o título Do Lado Errado do Mundo com lançamento previsto para o segundo semestre de 2016. O disco contará com 12 faixas produzidas pelo próprio artista.</p>
</div>