<div class="container">
    <div class="row">
        <div class="watch">
            <img class="img-responsive" src="images/watch.png" alt="">
        </div>				
        <div class="col-md-4 col-md-offset-2 col-sm-5">
            <h2><?php echo $this->translate('Nossos próximos eventos'); ?></h2>
        </div>				
        <div class="col-sm-7 col-md-6">					
            <iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=250&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=acacio.vilela%40gmail.com&amp;color=%231B887A&amp;ctz=America%2FSao_Paulo" style="border-width:0" width="400" height="250" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>
</div>