<div class="contact-section">
    <div class="ear-piece">
        <img class="img-responsive" src="images/ear-piece.png" alt="">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-3 col-sm-offset-4">
                <div class="contact-text">
                    <h3><?php echo $this->translate('Contato'); ?></h3>
                    <address>
                        E-mail: contato@acaciovilela.com<br>
                        <?php echo $this->translate('Fone'); ?>: +55 (34) 9 9937-4219 <i class="fa fa-whatsapp"></i><br>
                    </address>
                </div>
                <!--                    <div class="contact-address">
                                        <h3><?php echo $this->translate('Local'); ?></h3>
                                        <address>
                <?php echo $this->translate('Brasil'); ?>
                                        </address>
                                    </div>-->
            </div>
            <div class="col-sm-5">
                <div id="contact-section">
                    <h3><?php echo $this->translate('Envia sua mensagem'); ?></h3>
                    <div class="status alert alert-success" style="display: none"></div>
                    <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control" required="required" placeholder="<?php echo $this->translate('Nome'); ?>">
                        </div>
                        <div class="form-group">
                            <input type="email" name="email" class="form-control" required="required" placeholder="<?php echo $this->translate('Email'); ?>">
                        </div>
                        <div class="form-group">
                            <textarea name="message" id="message" required="required" class="form-control" rows="4" placeholder="<?php echo $this->translate('Digite sua mensagem'); ?>"></textarea>
                        </div>                        
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary pull-right"><?php echo $this->translate('Send'); ?></button>
                        </div>
                    </form>	       
                </div>
            </div>
        </div>
    </div>
</div>