<div class="main-nav">
    <div class="container">
        <div class="header-top">
            <div class="pull-right social-icons">
                <a href="http://facebook.com/acaciovilelamusic"><i class="fa fa-facebook"></i></a>
                <a href="https://www.youtube.com/channel/UCZlmAcbCGvLAHC2XF5e29lg"><i class="fa fa-youtube"></i></a>
                <a href="http://instagram.com/acaciovilela"><i class="fa fa-instagram"></i></a>
                <a href="http://twitter.com/acaciovilelaon"><i class="fa fa-twitter"></i></a>
                <a href="http://soundcloud.com/acaciovilela"><i class="fa fa-soundcloud"></i></a>
                <a href="https://plus.google.com/u/0/116926935759493174255"><i class="fa fa-google-plus"></i></a>
            </div>
        </div>     
        <div class="row">	        		
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath(); ?>">
                    <img class="img-responsive" src="images/logo.png" alt="logo">
                </a>                    
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">                 
                    <li class="scroll active"><a href="#home"><?php echo $this->translate('Home'); ?></a></li>
                    <li class="scroll"><a href="#about"><?php echo $this->translate('Release'); ?></a></li>                     
                    <li class="scroll"><a href="#explore"><?php echo $this->translate('Agenda'); ?></a></li>                         
                    <li class="scroll"><a href="#event"><?php echo $this->translate('Fotos'); ?></a></li>
                    <li class="scroll"><a href="#sponsor"><?php echo $this->translate('Videos'); ?></a></li>
                    <li class="scroll"><a href="#twitter"><?php echo $this->translate('Social'); ?></a></li>
                    <li class="scroll"><a href="#contact"><?php echo $this->translate('Contato'); ?></a></li>       
                </ul>
            </div>
        </div>
    </div>
</div>