<div id="main-slider" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#main-slider" data-slide-to="0" class="active"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img class="img-responsive" src="images/slider/bg1.jpg" alt="slider">						
            <div class="carousel-caption">
                <h2> <?php echo $this->translate('Fique ligado na agenda'); ?></h2>
                <h4><?php echo $this->translate(''); ?></h4>
                <a href="#explore"><?php echo $this->translate('Confira'); ?> <i class="fa fa-angle-right"></i></a>
            </div>
        </div>
    </div>
</div>