<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-9">
            <div id="event-carousel" class="carousel slide" data-interval="false">
                <h2 class="heading"><?php echo $this->translate('FOTOS'); ?></h2>
                <a class="even-control-left" href="#event-carousel" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                <a class="even-control-right" href="#event-carousel" data-slide="next"><i class="fa fa-angle-right"></i></a>
                <div class="carousel-inner">
                    <div class="item active">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="single-event">
                                    <img class="img-responsive" src="images/event/event1.jpg" alt="event-image">
                                    <h4>Santa Brasa</h4>
                                    <h5>27/03/2016</h5>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="single-event">
                                    <img class="img-responsive" src="images/event/event2.jpg" alt="event-image">
                                    <h4>Bar & Petiscaria do Marcelo</h4>
                                    <h5>30/03/2015</h5>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="single-event">
                                    <img class="img-responsive" src="images/event/event3.jpg" alt="event-image">
                                    <h4>Flash Back Night</h4>
                                    <h5>30/03/2015</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="guitar">
            <img class="img-responsive" src="images/guitar.png" alt="guitar">
        </div>
    </div>			
</div>