<div id="sponsor-carousel" class="carousel slide" data-interval="false">
    <div class="container">
        <div class="row">
            <div class="col-sm-10">
                <h2><?php echo $this->translate('Videos'); ?></h2>			
                <a class="sponsor-control-left" href="#sponsor-carousel" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                <a class="sponsor-control-right" href="#sponsor-carousel" data-slide="next"><i class="fa fa-angle-right"></i></a>
                <div class="carousel-inner">
                    <div class="item active">
                        <ul>
                            <!--<li style="width:100px;"><div style="width:100px;"><?php echo $this->video; ?></div></li>-->
                        </ul>
                    </div>
                </div>
            </div>
        </div>				
    </div>
    <div class="light">
        <img class="img-responsive" src="images/light.png" alt="">
    </div>
</div>