<header id="header" role="banner">		
    <?php echo $this->partial('layout/header'); ?>
</header>
<!--/#header-->

<section id="home">	
    <?php echo $this->partial('layout/home'); ?>
</section>
<!--/#home-->

<section id="about">
    <?php echo $this->partial('layout/about'); ?>
</section>

<!--/#about-->

<section id="explore">
    <?php echo $this->partial('layout/calendar'); ?>
</section>

<!--/#explore-->

<section id="event">
    <?php echo $this->partial('layout/pictures'); ?>
</section>

<section id="sponsor">
    <?php echo $this->partial('layout/videos'); ?>
</section>

<!--/#event-->

<section id="twitter">
    <?php echo $this->partial('layout/social'); ?>
</section><!--/#twitter-feed-->

<section id="contact">
    <?php echo $this->partial('layout/contact'); ?>
</section>
<!--/#contact-->

<footer id="footer">
    <?php echo $this->partial('layout/footer'); ?>
</footer>
<!--/#footer-->
